import htmlParser from '@html-eslint/parser'
import rule from '../lib/rules/no-unsafe-output-context.js'
import {html, inEngine} from './testers.js'

const {ERB} = htmlParser.TEMPLATE_ENGINE_SYNTAX
const as = inEngine

const error = (messageId, output, data = {}) => ({messageId, data: {output, ...data}})

html.run('no-unsafe-output-context', rule, {
  valid: [
    as('jinja', {name: 'text content', code: '<p>{{ user.name }}</p>'}),
    as('jinja', {name: 'quoted attribute', code: '<input value="{{ user.name }}">'}),
    as('jinja', {name: 'statement in a tag', code: '<input type="checkbox" {% if on %}checked{% endif %}>'}),
    as('jinja', {name: 'comment in script', code: '<script>{# user.name #}init()</script>'}),
    as('jinja', {name: 'tojson in script', code: '<script>const user = {{ user|tojson }}</script>'}),
    as('jinja', {name: 'tojson with whitespace control', code: '<script>const user = {{- user | tojson -}}</script>'}),
    as('jinja', {name: 'escapejs (Django) in a handler', code: '<button onclick="go(\'{{ name|escapejs }}\')"></button>'}),
    as('jinja', {name: 'number filter', code: '<script>const id = {{ post.id|int }}</script>'}),
    as('jinja', {name: 'fixed strings', code: '<script>const mode = {{ "dark" if dark else "light" }}</script>'}),
    as('jinja', {name: 'xmlattr writes escaped attributes', code: '<div {{ attrs|xmlattr }}></div>'}),
    as('jinja', {name: 'template script type', code: '<script type="text/template"><p>{{ name }}</p></script>'}),
    as('jinja', {name: 'URLs are opt-in', code: '<a href="{{ user.website }}">x</a>'}),
    as('jinja', {name: 'URL output after a fixed path', options: [{urls: true}], code: '<a href="/users/{{ user.id }}">x</a>'}),
    as('jinja', {name: 'url_for', options: [{urls: true}], code: '<a href="{{ url_for(\'user\', id=1) }}">x</a>'}),
    as('jinja', {name: 'constant from settings', options: [{urls: true}], code: '<link rel="stylesheet" href="{{ STATIC_URL }}a.css">'}),
    as('jinja', {name: 'custom URL helper', options: [{urls: true, urlHelpers: ['safe_url']}], code: '<a href="{{ user.website|safe_url }}">x</a>'}),
    as('jinja', {name: 'custom escaper', options: [{escapers: ['js_string']}], code: '<script>const n = "{{ name|js_string }}"</script>'}),
    as('jinja', {name: 'x-cloak is not code', code: '<div x-cloak x-ref="{{ ref }}"></div>'}),
    as('jinja', {name: 'hx-vals JSON', code: '<div hx-vals=\'{"id": "{{ id }}"}\'></div>'}),
    as('twig', {name: 'escape for js', code: '<script>const n = "{{ name|e(\'js\') }}"</script>'}),
    as('twig', {name: 'Drupal attributes', code: '<div{{ attributes }}></div>'}),
    as('twig', {name: 'Symfony UX stimulus', code: '<form {{ stimulus_controller(\'login\') }}></form>'}),
    as('liquid', {name: 'shopify_attributes', code: '<div {{ block.shopify_attributes }}></div>'}),
    as('blade', {name: '@{{ }} prints braces for Vue', code: '<script>const tpl = "@{{ name }}"</script>'}),
    as('blade', {name: 'comment', code: '<script>{{-- $user->name --}}init()</script>'}),
    as('blade', {name: 'Js::from', code: '<script>const user = {{ Js::from($user) }}</script>'}),
    as('blade', {name: 'conditional fixed strings in a tag', code: '<div {{ $open ? \'open\' : \'\' }}></div>'}),
    as('blade', {name: 'attribute bag', code: '<div {{ $attributes->merge([\'class\' => \'card\']) }}></div>'}),
    as('erb', {name: 'code tag', code: '<script><% if admin %>init()<% end %></script>'}),
    as('erb', {name: '<%- is code in ERB', code: '<script><%- if admin -%>init()<%- end -%></script>'}),
    as('erb', {name: 'j()', code: '<script>const n = "<%= j name %>"</script>'}),
    as('erb', {name: 'json_escape', code: '<script>const user = <%= raw json_escape(user.to_json) %></script>'}),
    as('handlebars', {name: 'block helpers', code: '<script>{{#if admin}}init(){{/if}}</script>'}),
    as('handlebars', {name: 'comment', code: '<script>{{! user.name }}init()</script>'}),
    as('php', {name: 'code block', code: '<script><?php if ($admin): ?>init()<?php endif; ?></script>'}),
    as('php', {name: 'JSON_HEX_TAG', code: '<script>const user = <?= json_encode($user, JSON_HEX_TAG | JSON_HEX_APOS) ?></script>'}),
    as('php', {name: 'esc_js', code: '<button onclick="go(\'<?php echo esc_js($name); ?>\')"></button>'}),
    as('jsp', {name: 'custom tag attribute', code: '<c:if test="${user.admin}"><p>x</p></c:if>'}),
  ],
  invalid: [
    as('jinja', {name: 'in a script string', code: '<script>const name = "{{ user.name }}"</script>', errors: [error('script', '{{ user.name }}')]}),
    as('jinja', {name: 'in script code', code: '<script>const id = {{ post.id }}</script>', errors: [error('script', '{{ post.id }}')]}),
    as('jinja', {name: 'JSON-LD', code: '<script type="application/ld+json">{"name": "{{ title }}"}</script>', errors: [error('script', '{{ title }}')]}),
    as('jinja', {name: 'module', code: '<script type="module">init("{{ key }}")</script>', errors: [error('script', '{{ key }}')]}),
    as('jinja', {name: 'dump is not escaped for script', code: '<script>const user = {{ user|dump }}</script>', errors: [error('script', '{{ user|dump }}')]}),
    as('jinja', {name: 'event handler', code: '<button onclick="go(\'{{ name }}\')"></button>', errors: [error('scriptAttribute', '{{ name }}', {attribute: 'onclick'})]}),
    as('jinja', {name: 'htmx hx-on', code: '<div hx-on:click="alert(\'{{ msg }}\')"></div>', errors: [error('scriptAttribute', '{{ msg }}', {attribute: 'hx-on:click'})]}),
    as('jinja', {name: 'htmx hx-vals with js:', code: '<div hx-vals="js:{q: \'{{ q }}\'}"></div>', errors: [error('scriptAttribute', '{{ q }}', {attribute: 'hx-vals'})]}),
    as('jinja', {name: 'Alpine x-data', code: '<div x-data="{name: \'{{ name }}\'}"></div>', errors: [error('scriptAttribute', '{{ name }}', {attribute: 'x-data'})]}),
    as('jinja', {name: 'Alpine @click', code: '<div @click="open(\'{{ id }}\')"></div>', errors: [error('scriptAttribute', '{{ id }}', {attribute: '@click'})]}),
    as('jinja', {name: 'Alpine :class', code: '<div :class="\'{{ cls }}\'"></div>', errors: [error('scriptAttribute', '{{ cls }}', {attribute: ':class'})]}),
    as('jinja', {name: 'Knockout', code: '<div data-bind="text: \'{{ name }}\'"></div>', errors: [error('scriptAttribute', '{{ name }}', {attribute: 'data-bind'})]}),
    as('jinja', {name: 'srcdoc', code: '<iframe srcdoc="<p>{{ comment }}</p>"></iframe>', errors: [error('srcdoc', '{{ comment }}')]}),
    as('jinja', {
      name: 'unquoted value',
      code: '<input value={{ name }}>',
      output: '<input value="{{ name }}">',
      errors: [error('unquoted', '{{ name }}')],
    }),
    as('jinja', {
      name: 'unquoted value with double quotes inside the tag',
      code: '<input value={{ name|default("x") }}>',
      output: '<input value=\'{{ name|default("x") }}\'>',
      errors: [error('unquoted', '{{ name|default("x") }}')],
    }),
    as('jinja', {
      name: 'unquoted event handler',
      code: '<a onclick=go({{ id }})>x</a>',
      output: '<a onclick="go({{ id }})">x</a>',
      errors: [error('unquoted', '{{ id }}'), error('scriptAttribute', '{{ id }}', {attribute: 'onclick'})],
    }),
    as('jinja', {name: 'attribute name', code: '<div {{ extra }}></div>', errors: [error('attributeName', '{{ extra }}')]}),
    as('jinja', {name: 'URL scheme', options: [{urls: true}], code: '<a href="{{ user.website }}">x</a>', errors: [error('url', '{{ user.website }}', {attribute: 'href'})]}),
    as('jinja', {name: 'URL after whitespace', options: [{urls: true}], code: '<form action=" {{ next }}"></form>', errors: [error('url', '{{ next }}', {attribute: 'action'})]}),
    as('jinja', {name: 'URL after a statement', options: [{urls: true}], code: '<a href="{% if x %}{% endif %}{{ link }}">x</a>', errors: [error('url', '{{ link }}', {attribute: 'href'})]}),
    as('liquid', {name: 'output', code: '<script>const t = "{{ \'cart.error\' | t }}"</script>', errors: [error('script', '{{ \'cart.error\' | t }}')]}),
    as('blade', {name: 'raw output', code: '<script>const n = "{!! $name !!}"</script>', errors: [error('script', '{!! $name !!}')]}),
    as('blade', {name: 'escaped output', code: '<button onclick="go(\'{{ $name }}\')"></button>', errors: [error('scriptAttribute', '{{ $name }}', {attribute: 'onclick'})]}),
    as('erb', {name: 'escaped output', code: '<script>const n = "<%= name %>"</script>', errors: [error('script', '<%= name %>')]}),
    as('erb', {name: 'raw output', code: '<script>const n = <%== data %></script>', errors: [error('script', '<%== data %>')]}),
    as('ejs', {name: '<%- is raw output in EJS', code: '<script>const n = "<%- name %>"</script>', errors: [error('script', '<%- name %>')]}),
    as('handlebars', {name: 'triple-stash', code: '<script>const n = "{{{ name }}}"</script>', errors: [error('script', '{{{ name }}}')]}),
    as('handlebars', {name: 'escaped', code: '<a onclick="go(\'{{ name }}\')">x</a>', errors: [error('scriptAttribute', '{{ name }}', {attribute: 'onclick'})]}),
    as('php', {name: 'short echo', code: '<script>const n = "<?= $name ?>"</script>', errors: [error('script', '<?= $name ?>')]}),
    as('php', {name: 'echo', code: '<a onclick="go(\'<?php echo $name; ?>\')">x</a>', errors: [error('scriptAttribute', '<?php echo $name; ?>', {attribute: 'onclick'})]}),
    as('php', {name: 'json_encode without JSON_HEX_TAG', code: '<script>const u = <?= json_encode($user) ?></script>', errors: [error('script', '<?= json_encode($user) ?>')]}),
    as('php', {name: 'attributes from a variable', code: '<div <?php echo $attrs; ?>></div>', errors: [error('attributeName', '<?php echo $attrs; ?>')]}),
    as('jsp', {name: 'EL in script', code: '<script>const n = "${name}"</script>', errors: [error('script', '${name}')]}),
    as('jsp', {name: 'Spring form tag passes onclick through', code: '<form:input path="q" onclick="go(\'${q}\')"/>', errors: [error('scriptAttribute', '${q}', {attribute: 'onclick'})]}),
    as('jsp', {name: 'expression in a handler', code: '<a onclick="go(\'<%= name %>\')">x</a>', errors: [error('scriptAttribute', '<%= name %>', {attribute: 'onclick'})]}),
  ],
})

html.run('no-unsafe-output-context (engine from the file name)', rule, {
  valid: [
    {name: '.erb: <%- is code', filename: 'show.html.erb', languageOptions: {parserOptions: {templateEngineSyntax: ERB}}, code: '<script><%- if a -%>x()<%- end -%></script>'},
    {name: 'plain HTML has no template parts', code: '<script>const n = "{{ name }}"</script>'},
  ],
  invalid: [
    {name: '.ejs: <%- is output', filename: 'page.ejs', languageOptions: {parserOptions: {templateEngineSyntax: ERB}}, code: '<script><%- a %></script>', errors: [error('script', '<%- a %>')]},
    {name: 'no engine: <%- counts as output', languageOptions: {parserOptions: {templateEngineSyntax: ERB}}, code: '<script><%- a %></script>', errors: [error('script', '<%- a %>')]},
  ],
})
