import rule from '../lib/rules/no-unescaped-output.js'
import {html, inEngine as as} from './testers.js'

const unescaped = (output, fix) => ({messageId: 'unescaped', data: {output, fix}})

html.run('no-unescaped-output', rule, {
  valid: [
    as('jinja', {name: 'escaped output', code: '<p>{{ comment.body }}</p>'}),
    as('jinja', {name: 'escaped attribute', code: '<a title="{{ user.name }}">x</a>'}),
    as('jinja', {name: 'statement', code: '<p>{% if a %}x{% endif %}</p>'}),
    as('jinja', {name: 'autoescape on', code: '{% autoescape true %}<p>{{ a }}</p>{% endautoescape %}'}),
    as('jinja', {name: 'constant marked safe', code: '<p>{{ "&nbsp;"|safe }}</p>'}),
    as('jinja', {name: 'sanitized, then safe', options: [{sanitizers: ['bleach']}], code: '<p>{{ post.body|bleach|safe }}</p>'}),
    as('jinja', {name: 'script content is no-unsafe-output-context\'s', code: '<script>const a = {{ data|safe }}</script>'}),
    as('jinja', {name: 'event handlers are no-unsafe-output-context\'s', code: '<a onclick="go({{ id|safe }})">x</a>'}),
    as('twig', {name: 'escape filter', code: '<p>{{ a|e|raw }}</p>'}),
    as('blade', {name: 'escaped', code: '<p>{{ $comment->body }}</p>'}),
    as('blade', {name: 'e() inside raw output', code: '<p>{!! nl2br(e($comment->body)) !!}</p>'}),
    as('blade', {name: 'CSRF field', code: '<form>{!! csrf_field() !!}</form>'}),
    as('blade', {name: 'pagination', code: '<nav>{!! $posts->links() !!}</nav>'}),
    as('blade', {name: 'Purifier::clean', code: '<div>{!! Purifier::clean($html) !!}</div>'}),
    as('handlebars', {name: 'escaped', code: '<p>{{ name }}</p>'}),
    as('handlebars', {name: 'layout body', code: '<main>{{{body}}}</main>'}),
    as('erb', {name: 'escaped', code: '<p><%= comment.body %></p>'}),
    as('erb', {name: 'html_safe inside an argument', code: '<p><%= confirm_url(token: token.html_safe) %></p>'}),
    as('erb', {name: 'sanitize', code: '<p><%= raw sanitize(post.body) %></p>'}),
    as('ejs', {name: 'escaped', code: '<p><%= name %></p>'}),
    as('ejs', {name: 'include', code: '<body><%- include(\'header\') %></body>'}),
    as('ejs', {name: 'layout body', code: '<main><%- body %></main>'}),
    as('php', {name: 'htmlspecialchars', code: '<p><?= htmlspecialchars($name) ?></p>'}),
    as('php', {name: 'esc_html', code: '<p><?php echo esc_html( $title ); ?></p>'}),
    as('php', {name: 'integer cast', code: '<p><?= (int) $count ?></p>'}),
    as('php', {name: 'fixed strings', code: '<p><?php echo $open ? \'open\' : \'closed\'; ?></p>'}),
    as('php', {name: 'code block', code: '<p><?php if ($a): ?>x<?php endif; ?></p>'}),
    as('jsp', {name: 'escapeXml', code: '<p>${fn:escapeXml(name)}</p>'}),
    as('jsp', {name: 'tag library attribute', code: '<c:out value="${name}"/>'}),
    as('jsp', {name: 'comment', code: '<p><%-- owner name --%></p>'}),
    as('liquid', {name: 'Liquid escapes nothing, so it is not checked', code: '<p>{{ product.title }}</p>'}),
    {name: 'no engine syntax', code: '<p>{{{ raw }}}</p>'},
  ],
  invalid: [
    as('jinja', {name: '|safe', code: '<p>{{ comment.body|safe }}</p>', errors: [unescaped('{{ comment.body|safe }}', 'Remove `|safe`')]}),
    as('jinja', {name: '| safe in an attribute', code: '<a title="{{ user.name | safe }}">x</a>', errors: [unescaped('{{ user.name | safe }}', 'Remove `|safe`')]}),
    as('jinja', {name: 'safeseq', code: '<p>{{ items|safeseq|join(", ") }}</p>', errors: [unescaped('{{ items|safeseq|join(", ") }}', 'Remove `|safe`')]}),
    as('jinja', {name: 'in <style>', code: '<style>{{ css|safe }}</style>', errors: [unescaped('{{ css|safe }}', 'Remove `|safe`')]}),
    as('jinja', {name: 'in <textarea>', code: '<textarea>{{ draft|safe }}</textarea>', errors: [unescaped('{{ draft|safe }}', 'Remove `|safe`')]}),
    as('jinja', {
      name: 'autoescape false',
      code: '{% autoescape false %}<p>{{ a }}</p>{% endautoescape %}',
      errors: [{messageId: 'autoescapeOff', data: {output: '{% autoescape false %}'}}],
    }),
    as('jinja', {
      name: 'autoescape off (Django)',
      code: '<div>{% autoescape off %}{{ a }}{% endautoescape %}</div>',
      errors: [{messageId: 'autoescapeOff', data: {output: '{% autoescape off %}'}}],
    }),
    as('twig', {name: '|raw', code: '<p>{{ \'help\'|trans|raw }}</p>', errors: [unescaped('{{ \'help\'|trans|raw }}', 'Remove `|raw`')]}),
    as('blade', {name: '{!! !!}', code: '<div>{!! $page->html !!}</div>', errors: [unescaped('{!! $page->html !!}', 'Use `{{ }}`')]}),
    as('handlebars', {name: 'triple-stash', code: '<p>{{{ bio }}}</p>', errors: [unescaped('{{{ bio }}}', 'Use `{{ }}`')]}),
    as('handlebars', {name: '{{& }}', code: '<p>{{& bio }}</p>', errors: [unescaped('{{& bio }}', 'Use `{{ }}`')]}),
    {
      name: 'handlebars: triple-stash read with `{{` delimiters only',
      languageOptions: {parserOptions: {templateEngineSyntax: {'{{': '}}'}}},
      code: '<p>{{{ bio }}}</p>',
      errors: [unescaped('{{{ bio }}', 'Use `{{ }}`')],
    },
    as('erb', {name: '<%==', code: '<p><%== post.body %></p>', errors: [unescaped('<%== post.body %>', 'Use `<%= %>`')]}),
    as('erb', {name: 'raw()', code: '<p><%= raw post.body %></p>', errors: [unescaped('<%= raw post.body %>', 'Remove `raw` / `html_safe`')]}),
    as('erb', {name: 'html_safe', code: '<p><%= post.body.html_safe %></p>', errors: [unescaped('<%= post.body.html_safe %>', 'Remove `raw` / `html_safe`')]}),
    as('ejs', {name: '<%-', code: '<p><%- post.content %></p>', errors: [unescaped('<%- post.content %>', 'Use `<%= %>`')]}),
    as('php', {name: 'short echo', code: '<p><?= $name ?></p>', errors: [unescaped('<?= $name ?>', 'Wrap it in `htmlspecialchars()` or `esc_html()`')]}),
    as('php', {name: 'echo', code: '<a title="<?php echo $title; ?>">x</a>', errors: [unescaped('<?php echo $title; ?>', 'Wrap it in `htmlspecialchars()` or `esc_html()`')]}),
    as('php', {name: 'function with a longer name', code: '<p><?= get_the_title() ?></p>', errors: [unescaped('<?= get_the_title() ?>', 'Wrap it in `htmlspecialchars()` or `esc_html()`')]}),
    as('jsp', {name: 'EL in text', code: '<p>${owner.name}</p>', errors: [unescaped('${owner.name}', 'Use `<c:out>` or `fn:escapeXml()`')]}),
    as('jsp', {name: 'EL in an attribute', code: '<a title="${owner.name}">x</a>', errors: [unescaped('${owner.name}', 'Use `<c:out>` or `fn:escapeXml()`')]}),
    as('jsp', {name: 'expression', code: '<p><%= name %></p>', errors: [unescaped('<%= name %>', 'Use `<c:out>` or `fn:escapeXml()`')]}),
  ],
})
